apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3  # Increase replicas for high availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "mp-backend-app"  #{{ .Values.appimage }}"  # Replace with your custom backend image
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"  # Connect to the Redis service
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
