apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 3  # Increase replicas for high availability
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data  # Redis stores data in this directory
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
